import { ref, computed, watch, nextTick, onMounted, onUnmounted } from 'vue'
import type { WizardNode, WizardEdge, EdgePath, PaletteEventDef, EventSource } from '@/types/wizard'
import { paletteSections } from '@/data/palette'

export const CAT_META: Record<string, { iconBox: string; bar: string; badge: string }> = {
  extract: { iconBox: 'border-vn-accent/20 bg-vn-accent/10 text-vn-accent', bar: '#00e5ff', badge: '#00e5ff' },
  transform: { iconBox: 'border-vn-accent2/20 bg-vn-accent2/10 text-vn-accent2', bar: '#7b61ff', badge: '#7b61ff' },
  load: { iconBox: 'border-vn-attr/20 bg-vn-attr/10 text-vn-attr', bar: '#ffb830', badge: '#ffb830' },
  ai: { iconBox: 'border-vn-pink/20 bg-vn-pink/10 text-vn-pink', bar: '#ff6eb4', badge: '#ff6eb4' },
  validate: { iconBox: 'border-vn-accent3/20 bg-vn-accent3/10 text-vn-accent3', bar: '#00ff94', badge: '#00ff94' },
  notify: { iconBox: 'border-vn-teal/20 bg-vn-teal/10 text-vn-teal', bar: '#00d4aa', badge: '#00d4aa' },
  control: { iconBox: 'border-vn-wizard-fog2/20 bg-vn-wizard-fog/15 text-vn-wizard-fog2', bar: '#5a6d85', badge: '#5a6d85' },
}

const PALETTE_STRIPE: Record<string, string> = {
  extract: 'before:bg-vn-accent',
  transform: 'before:bg-vn-accent2',
  load: 'before:bg-vn-attr',
  ai: 'before:bg-vn-pink',
  validate: 'before:bg-vn-accent3',
  notify: 'before:bg-vn-teal',
  control: 'before:bg-vn-wizard-fog2',
}

export function paletteStripeColor(cat: string) {
  return PALETTE_STRIPE[cat] ?? 'before:bg-vn-wizard-fog2'
}

export const SOURCE_COLORS: Record<EventSource, string> = {
  pypi: '#00e5ff',
  hub: '#ffb830',
  git: '#7b61ff',
  local: '#00ff94',
}

function eventAbbr(type: string) {
  return type
    .replace(/[a-z]/g, '')
    .slice(0, 3)
    .padEnd(2, type[1] || 'X')
}

/** Port handles are explicit elements — avoids ambiguity with nested `.port` wrappers and `input` class clashes. */
const PORT_OUT = '[data-port="out"]'
const PORT_IN = '[data-port="in"]'

/** Pixels from port center to count as a drop (handles are ~44px; keep generous). */
const PORT_SNAP_PX = 44

function getPortCenter(nodeId: string, side: 'out' | 'in', wrap: HTMLElement) {
  const nodeEl = document.getElementById(nodeId)
  if (!nodeEl) return { x: 0, y: 0 }
  const sel = side === 'out' ? PORT_OUT : PORT_IN
  const portEl = nodeEl.querySelector(sel) as HTMLElement | null
  if (!portEl) return { x: 0, y: 0 }
  const wrapRect = wrap.getBoundingClientRect()
  const pr = portEl.getBoundingClientRect()
  return {
    x: pr.left - wrapRect.left + pr.width / 2,
    y: pr.top - wrapRect.top + pr.height / 2,
  }
}

function renderNodeHtml(node: WizardNode): string {
  const ver = node.version.trim() || '@latest'
  const annParts: string[] = []
  if (node.annotation.trim()) annParts.push(node.annotation.trim())
  if (node.executor) annParts.push(`executor="${node.executor}"`)
  const ann = annParts.length ? `[${annParts.join(', ')}]` : ''
  const retryStr = node.retry > 0 ? ` <span class="pt-rt">* ${node.retry}</span>` : ''
  const src = `<span class="pt-meta">${node.source}</span><span>:</span><span class="pt-nd">${node.type}</span><span class="pt-ann">${ver}</span>`
  const annStr = ann ? `<span class="pt-ann">${ann}</span>` : ''
  return src + annStr + retryStr
}

function buildPointyHtml(nodes: WizardNode[], edges: WizardEdge[], workflowName: string): string {
  if (nodes.length === 0) {
    return '<span class="pt-cm"># Add events to the canvas to generate Pointy-lang</span>'
  }

  const inDegree: Record<string, number> = {}
  nodes.forEach((n) => {
    inDegree[n.id] = 0
  })
  edges.forEach((e) => {
    inDegree[e.to] = (inDegree[e.to] ?? 0) + 1
  })
  const roots = nodes.filter((n) => inDegree[n.id] === 0)

  function renderNodeLine(node: WizardNode) {
    return renderNodeHtml(node)
  }

  function buildChain(startId: string, visited: Set<string>): string {
    if (visited.has(startId)) return ''
    visited.add(startId)
    const node = nodes.find((n) => n.id === startId)
    if (!node) return ''
    const outEdges = edges.filter((e) => e.from === startId)
    let line = renderNodeLine(node)
    if (outEdges.length === 0) return line
    if (outEdges.length === 1) {
      const next = buildChain(outEdges[0]!.to, visited)
      return `${line}\n  <span class="pt-arr">-></span> ${next}`
    }
    const branches = outEdges.map((e) => buildChain(e.to, new Set(visited))).join('\n  <span class="pt-op">|-></span> ')
    return `${line}\n  <span class="pt-op">|-></span> ${branches}`
  }

  const name = workflowName.trim() || 'workflow'
  let html = `<span class="pt-cm"># ${name}.pointy — generated by Pointy-lang Wizard</span>\n\n`
  if (roots.length === 0 && nodes.length > 0) {
    html += nodes.map((n) => renderNodeLine(n)).join('\n  <span class="pt-arr">-></span> ')
  } else {
    html += roots.map((r) => buildChain(r.id, new Set())).join('\n\n')
  }
  return html
}

export function usePointyWizard() {
  const canvasWrapRef = ref<HTMLElement | null>(null)
  const dragGhostRef = ref<HTMLElement | null>(null)
  const pointyOutputRef = ref<HTMLElement | null>(null)

  const nodes = ref<WizardNode[]>([])
  const edges = ref<WizardEdge[]>([])
  const selectedNodeId = ref<string | null>(null)
  const currentTool = ref<'select' | 'connect' | 'pan'>('select')
  const zoomLevel = ref(1)
  let nodeCounter = 0
  let edgeCounter = 0

  const workflowName = ref('untitled-workflow')
  const paletteSearch = ref('')
  const collapsed = ref<Record<string, boolean>>({})

  const rightPanelCollapsed = ref(false)
  const bottomTab = ref<'pointy' | 'console' | 'validation'>('pointy')

  const modalOpen = ref(false)
  const modalName = ref('my-etl-pipeline')
  const selectedTemplate = ref('Blank')

  const ctxVisible = ref(false)
  const ctxX = ref(0)
  const ctxY = ref(0)
  const ctxTargetId = ref<string | null>(null)
  const ctxIsCanvas = ref(false)

  const liveEdgeD = ref('')
  const connectingFromId = ref<string | null>(null)
  /** When dragging a connection starting from an input port, this is the target node id. */
  const connectingToId = ref<string | null>(null)
  const connectingHoverId = ref<string | null>(null)

  const paletteWidth = ref(256)
  const rightPanelWidth = ref(240)
  const bottomPanelHeight = ref(110)

  const edgePaths = ref<EdgePath[]>([])
  const copyBtnFlash = ref(false)

  const zoomDisplay = computed(() => `${Math.round(zoomLevel.value * 100)}%`)

  const selectedNode = computed(() => nodes.value.find((n) => n.id === selectedNodeId.value) ?? null)

  const canvasEmpty = computed(() => nodes.value.length === 0)

  const filteredSections = computed(() => {
    const q = paletteSearch.value.trim().toLowerCase()
    if (!q) return paletteSections
    return paletteSections
      .map((sec) => ({
        ...sec,
        events: sec.events.filter((e) => e.type.toLowerCase().includes(q)),
      }))
      .filter((sec) => sec.events.length > 0)
  })

  const pointyHtml = computed(() => buildPointyHtml(nodes.value, edges.value, workflowName.value))

  function setTool(tool: 'select' | 'connect' | 'pan') {
    currentTool.value = tool
  }

  function zoom(delta: number) {
    zoomLevel.value = Math.min(2, Math.max(0.3, zoomLevel.value + delta))
  }

  function fitCanvas() {
    zoomLevel.value = 1
  }

  function toggleSection(id: string) {
    collapsed.value = { ...collapsed.value, [id]: !collapsed.value[id] }
  }

  function metaFor(cat: string) {
    return CAT_META[cat] ?? CAT_META.control!
  }

  function srcColor(source: EventSource) {
    return SOURCE_COLORS[source] ?? '#5a6d85'
  }

  async function refreshEdges() {
    await nextTick()
    const wrap = canvasWrapRef.value
    if (!wrap) {
      edgePaths.value = []
      return
    }

    wrap.querySelectorAll('[data-port]').forEach((el) => el.classList.remove('port-is-connected'))

    const paths: EdgePath[] = []
    for (const edge of edges.value) {
      const fromNode = nodes.value.find((n) => n.id === edge.from)
      const toNode = nodes.value.find((n) => n.id === edge.to)
      if (!fromNode || !toNode) continue

      const from = getPortCenter(edge.from, 'out', wrap)
      const to = getPortCenter(edge.to, 'in', wrap)
      const cx = (from.x + to.x) / 2
      const d = `M${from.x},${from.y} C${cx},${from.y} ${cx},${to.y} ${to.x},${to.y}`
      const mx = (from.x + to.x) / 2
      const my = (from.y + to.y) / 2
      paths.push({ id: edge.id, d, mx, my })

      document.getElementById(edge.from)?.querySelector(PORT_OUT)?.classList.add('port-is-connected')
      document.getElementById(edge.to)?.querySelector(PORT_IN)?.classList.add('port-is-connected')
    }
    edgePaths.value = paths
  }

  watch([nodes, edges], () => void refreshEdges(), { deep: true })

  function addNode(
    type: string,
    cat: string,
    source: EventSource,
    _color: string,
    x: number,
    y: number,
  ) {
    const id = `n${++nodeCounter}`
    const meta = metaFor(cat)
    const node: WizardNode = {
      id,
      type,
      cat,
      source,
      color: meta.bar,
      x,
      y,
      annotation: '',
      version: '@latest',
      executor: '',
      retry: 0,
    }
    nodes.value = [...nodes.value, node]
    selectedNodeId.value = id
    void refreshEdges()
  }

  function deleteNode(id: string) {
    nodes.value = nodes.value.filter((n) => n.id !== id)
    edges.value = edges.value.filter((e) => e.from !== id && e.to !== id)
    if (selectedNodeId.value === id) selectedNodeId.value = null
    hideCtx()
    void refreshEdges()
  }

  function duplicateNode(id: string) {
    const node = nodes.value.find((n) => n.id === id)
    if (!node) return
    addNode(node.type, node.cat, node.source, node.color, node.x + 180, node.y + 24)
  }

  function selectNode(id: string | null) {
    selectedNodeId.value = id
  }

  function patchNode(id: string, patch: Partial<WizardNode>) {
    const i = nodes.value.findIndex((n) => n.id === id)
    if (i === -1) return
    const copy = [...nodes.value]
    copy[i] = { ...copy[i]!, ...patch }
    nodes.value = copy
  }

  function onCanvasMouseDown(e: MouseEvent) {
    const t = e.target as Element
    if (!t.closest?.('.canvas-node')) selectNode(null)
    hideCtx()
  }

  function onNodeBodyPointerDown(e: PointerEvent, id: string) {
    const t = e.target as HTMLElement
    if (t.closest?.('[data-port]') || t.classList.contains('node-delete')) return
    e.preventDefault()
    selectNode(id)
    const node = nodes.value.find((n) => n.id === id)
    if (!node) return
    const ox = e.clientX
    const oy = e.clientY
    const mx = node.x
    const my = node.y

    const onMove = (ev: PointerEvent) => {
      node.x = mx + (ev.clientX - ox)
      node.y = my + (ev.clientY - oy)
      void refreshEdges()
    }
    const onUp = () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
    }
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }

  function startPaletteResize(e: PointerEvent) {
    e.preventDefault()
    e.stopPropagation()
    const startX = e.clientX
    const w0 = paletteWidth.value
    const onMove = (ev: PointerEvent) => {
      paletteWidth.value = Math.min(420, Math.max(180, w0 + (ev.clientX - startX)))
    }
    const onUp = () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
    }
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }

  function startRightPanelResize(e: PointerEvent) {
    e.preventDefault()
    e.stopPropagation()
    const startX = e.clientX
    const w0 = rightPanelWidth.value
    const onMove = (ev: PointerEvent) => {
      rightPanelWidth.value = Math.min(520, Math.max(200, w0 - (ev.clientX - startX)))
    }
    const onUp = () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
    }
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }

  function startBottomResize(e: PointerEvent) {
    e.preventDefault()
    e.stopPropagation()
    const startY = e.clientY
    const h0 = bottomPanelHeight.value
    const onMove = (ev: PointerEvent) => {
      bottomPanelHeight.value = Math.min(480, Math.max(72, h0 + (startY - ev.clientY)))
    }
    const onUp = () => {
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
    }
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }

  function onOutputPortDown(e: PointerEvent, id: string) {
    e.stopPropagation()
    e.preventDefault()
    connectingToId.value = null
    connectingFromId.value = id
    const wrap = canvasWrapRef.value
    if (!wrap) return

    const captureEl = e.currentTarget as HTMLElement | null
    if (captureEl?.setPointerCapture) {
      try {
        captureEl.setPointerCapture(e.pointerId)
      } catch {
        /* ignore */
      }
    }

    const onMove = (ev: PointerEvent) => {
      const fromPos = getPortCenter(id, 'out', wrap)
      const r = wrap.getBoundingClientRect()
      const tx = ev.clientX - r.left
      const ty = ev.clientY - r.top
      const cx = (fromPos.x + tx) / 2
      liveEdgeD.value = `M${fromPos.x},${fromPos.y} C${cx},${fromPos.y} ${cx},${ty} ${tx},${ty}`

      let hover: string | null = null
      for (const n of nodes.value) {
        if (n.id === id) continue
        const inPort = document.getElementById(n.id)?.querySelector(PORT_IN) as HTMLElement | undefined
        if (!inPort) continue
        const ir = inPort.getBoundingClientRect()
        const dist = Math.hypot(ev.clientX - (ir.left + ir.width / 2), ev.clientY - (ir.top + ir.height / 2))
        if (dist < PORT_SNAP_PX) hover = n.id
      }
      connectingHoverId.value = hover
    }

    const onUp = (ev: PointerEvent) => {
      liveEdgeD.value = ''
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
      window.removeEventListener('pointercancel', onUp)
      if (captureEl?.releasePointerCapture) {
        try {
          captureEl.releasePointerCapture(ev.pointerId)
        } catch {
          /* ignore */
        }
      }

      const fromId = connectingFromId.value
      connectingFromId.value = null
      connectingHoverId.value = null
      if (!fromId || !wrap) return

      for (const n of nodes.value) {
        if (n.id === fromId) continue
        const inPort = document.getElementById(n.id)?.querySelector(PORT_IN) as HTMLElement | undefined
        if (!inPort) continue
        const ir = inPort.getBoundingClientRect()
        const dist = Math.hypot(ev.clientX - (ir.left + ir.width / 2), ev.clientY - (ir.top + ir.height / 2))
        if (dist < PORT_SNAP_PX) {
          const dup = edges.value.find((ed) => ed.from === fromId && ed.to === n.id)
          if (!dup) {
            edges.value = [...edges.value, { id: `e${++edgeCounter}`, from: fromId, to: n.id }]
            void refreshEdges()
          }
          break
        }
      }
    }

    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
    window.addEventListener('pointercancel', onUp)
  }

  function onInputPortDown(e: PointerEvent, id: string) {
    e.stopPropagation()
    e.preventDefault()
    connectingFromId.value = null
    connectingToId.value = id
    const wrap = canvasWrapRef.value
    if (!wrap) return

    const captureEl = e.currentTarget as HTMLElement | null
    if (captureEl?.setPointerCapture) {
      try {
        captureEl.setPointerCapture(e.pointerId)
      } catch {
        /* ignore */
      }
    }

    const onMove = (ev: PointerEvent) => {
      const toPos = getPortCenter(id, 'in', wrap)
      let hover: string | null = null
      for (const n of nodes.value) {
        if (n.id === id) continue
        const outPort = document.getElementById(n.id)?.querySelector(PORT_OUT) as HTMLElement | undefined
        if (!outPort) continue
        const ir = outPort.getBoundingClientRect()
        const dist = Math.hypot(ev.clientX - (ir.left + ir.width / 2), ev.clientY - (ir.top + ir.height / 2))
        if (dist < PORT_SNAP_PX) hover = n.id
      }
      connectingHoverId.value = hover
      const r = wrap.getBoundingClientRect()
      if (hover) {
        const fromPos = getPortCenter(hover, 'out', wrap)
        const cx = (fromPos.x + toPos.x) / 2
        liveEdgeD.value = `M${fromPos.x},${fromPos.y} C${cx},${fromPos.y} ${cx},${toPos.y} ${toPos.x},${toPos.y}`
      } else {
        const tx = ev.clientX - r.left
        const ty = ev.clientY - r.top
        const cx = (tx + toPos.x) / 2
        liveEdgeD.value = `M${tx},${ty} C${cx},${ty} ${cx},${toPos.y} ${toPos.x},${toPos.y}`
      }
    }

    const onUp = (ev: PointerEvent) => {
      liveEdgeD.value = ''
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
      window.removeEventListener('pointercancel', onUp)
      if (captureEl?.releasePointerCapture) {
        try {
          captureEl.releasePointerCapture(ev.pointerId)
        } catch {
          /* ignore */
        }
      }

      const toId = connectingToId.value
      connectingToId.value = null
      connectingHoverId.value = null
      if (!toId || !wrap) return

      for (const n of nodes.value) {
        if (n.id === toId) continue
        const outPort = document.getElementById(n.id)?.querySelector(PORT_OUT) as HTMLElement | undefined
        if (!outPort) continue
        const ir = outPort.getBoundingClientRect()
        const dist = Math.hypot(ev.clientX - (ir.left + ir.width / 2), ev.clientY - (ir.top + ir.height / 2))
        if (dist < PORT_SNAP_PX) {
          const fromId = n.id
          if (fromId === toId) break
          const dup = edges.value.find((ed) => ed.from === fromId && ed.to === toId)
          if (!dup) {
            edges.value = [...edges.value, { id: `e${++edgeCounter}`, from: fromId, to: toId }]
            void refreshEdges()
          }
          break
        }
      }
    }

    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
    window.addEventListener('pointercancel', onUp)
  }

  function onNodeContextMenu(e: MouseEvent, id: string) {
    e.preventDefault()
    e.stopPropagation()
    ctxTargetId.value = id
    ctxIsCanvas.value = false
    ctxX.value = e.clientX
    ctxY.value = e.clientY
    ctxVisible.value = true
  }

  function onCanvasContextMenu(e: MouseEvent) {
    e.preventDefault()
    ctxTargetId.value = null
    ctxIsCanvas.value = true
    ctxX.value = e.clientX
    ctxY.value = e.clientY
    ctxVisible.value = true
  }

  function hideCtx() {
    ctxVisible.value = false
  }

  function ctxDelete() {
    if (ctxTargetId.value) deleteNode(ctxTargetId.value)
    hideCtx()
  }

  function ctxDuplicate() {
    if (ctxTargetId.value) duplicateNode(ctxTargetId.value)
    hideCtx()
  }

  function clearCanvas() {
    nodes.value = []
    edges.value = []
    selectedNodeId.value = null
    nodeCounter = 0
    edgeCounter = 0
    void refreshEdges()
  }

  function removeEdge(edgeId: string) {
    edges.value = edges.value.filter((e) => e.id !== edgeId)
    void refreshEdges()
  }

  function onPaletteDragStart(e: DragEvent, ev: PaletteEventDef) {
    const payload = JSON.stringify({
      type: ev.type,
      cat: ev.cat,
      source: ev.source,
      color: ev.color,
    })
    e.dataTransfer?.setData('text/plain', payload)
    e.dataTransfer!.effectAllowed = 'copy'
    const ghost = dragGhostRef.value
    if (ghost) {
      ghost.textContent = ev.type
      ghost.style.display = 'block'
      ghost.style.top = '-100px'
      ghost.style.left = '0'
      e.dataTransfer?.setDragImage(ghost, 0, 0)
    }
  }

  function onPaletteDragEnd() {
    const ghost = dragGhostRef.value
    if (ghost) ghost.style.display = 'none'
  }

  function onCanvasDragOver(e: DragEvent) {
    e.preventDefault()
    e.dataTransfer!.dropEffect = 'copy'
  }

  function onCanvasDrop(e: DragEvent) {
    e.preventDefault()
    const wrap = canvasWrapRef.value
    if (!wrap) return
    try {
      const data = JSON.parse(e.dataTransfer?.getData('text/plain') || '{}') as {
        type: string
        cat: string
        source: EventSource
        color: string
      }
      const rect = wrap.getBoundingClientRect()
      const x = e.clientX - rect.left - 80
      const y = e.clientY - rect.top - 30
      addNode(data.type, data.cat, data.source, data.color, x, y)
    } catch {
      /* ignore */
    }
  }

  function openNewWorkflowModal() {
    modalOpen.value = true
  }

  function closeModal() {
    modalOpen.value = false
  }

  function pickTemplate(name: string) {
    selectedTemplate.value = name
  }

  function delay(ms: number) {
    return new Promise<void>((r) => setTimeout(r, ms))
  }

  async function confirmNewWorkflow() {
    const name = modalName.value.trim() || 'my-workflow'
    workflowName.value = name
    closeModal()
    clearCanvas()
    await delay(100)
    const tmpl = selectedTemplate.value

    if (tmpl === 'ETL Pipeline') {
      addNode('PostgresExtract', 'extract', 'pypi', '#00e5ff', 60, 120)
      await delay(80)
      addNode('NormaliseTimestamps', 'transform', 'pypi', '#7b61ff', 280, 120)
      await delay(80)
      addNode('SnowflakeLoad', 'load', 'hub', '#ffb830', 500, 120)
      await delay(100)
      const n = nodeCounter
      edges.value = [
        ...edges.value,
        { id: `e${++edgeCounter}`, from: `n${n - 2}`, to: `n${n - 1}` },
        { id: `e${++edgeCounter}`, from: `n${n - 1}`, to: `n${n}` },
      ]
      void refreshEdges()
    } else if (tmpl === 'AI Agent') {
      addNode('RestApiExtract', 'extract', 'hub', '#00e5ff', 60, 100)
      await delay(80)
      addNode('ClassifyIntent', 'ai', 'hub', '#ff6eb4', 280, 100)
      await delay(80)
      addNode('GPT4Transform', 'ai', 'hub', '#ff6eb4', 500, 60)
      await delay(40)
      addNode('SlackNotify', 'notify', 'pypi', '#00d4aa', 500, 160)
      await delay(120)
      const n = nodeCounter
      edges.value = [
        ...edges.value,
        { id: `e${++edgeCounter}`, from: `n${n - 3}`, to: `n${n - 2}` },
        { id: `e${++edgeCounter}`, from: `n${n - 2}`, to: `n${n - 1}` },
        { id: `e${++edgeCounter}`, from: `n${n - 2}`, to: `n${n}` },
      ]
      void refreshEdges()
    } else if (tmpl === 'Streaming') {
      addNode('KafkaIngest', 'extract', 'pypi', '#00e5ff', 60, 120)
      await delay(80)
      addNode('SchemaValidate', 'validate', 'git', '#00ff94', 280, 120)
      await delay(80)
      addNode('RedisCache', 'load', 'git', '#ffb830', 500, 120)
      await delay(100)
      const n = nodeCounter
      edges.value = [
        ...edges.value,
        { id: `e${++edgeCounter}`, from: `n${n - 2}`, to: `n${n - 1}` },
        { id: `e${++edgeCounter}`, from: `n${n - 1}`, to: `n${n}` },
      ]
      void refreshEdges()
    }
  }

  async function copyPointy() {
    const el = pointyOutputRef.value
    const text = el?.innerText ?? ''
    await navigator.clipboard.writeText(text)
    copyBtnFlash.value = true
    setTimeout(() => {
      copyBtnFlash.value = false
    }, 1500)
  }

  function onEdgeEnter(e: Event) {
    const path = e.target as SVGPathElement
    path.classList.add('stroke-dasharray-[8_4]', 'animate-flow-dash')
  }

  function onEdgeLeave(e: Event) {
    const path = e.target as SVGPathElement
    path.classList.remove('stroke-dasharray-[8_4]', 'animate-flow-dash')
  }

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') closeModal()
    if ((e.metaKey || e.ctrlKey) && e.key === 'n') {
      e.preventDefault()
      openNewWorkflowModal()
    }
    if (e.key === 'Delete' || e.key === 'Backspace') {
      const tag = (e.target as HTMLElement)?.tagName
      if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return
      if (selectedNodeId.value) deleteNode(selectedNodeId.value)
    }
    if ((e.key === 'v' || e.key === 'V') && !e.metaKey && !e.ctrlKey) {
      const t = (e.target as HTMLElement)?.tagName
      if (t !== 'INPUT' && t !== 'TEXTAREA') setTool('select')
    }
    if ((e.key === 'h' || e.key === 'H') && !e.metaKey && !e.ctrlKey) {
      const t = (e.target as HTMLElement)?.tagName
      if (t !== 'INPUT' && t !== 'TEXTAREA') setTool('pan')
    }
  }

  onMounted(() => {
    document.addEventListener('click', hideCtx)
    document.addEventListener('keydown', onKeyDown)
  })

  onUnmounted(() => {
    document.removeEventListener('click', hideCtx)
    document.removeEventListener('keydown', onKeyDown)
  })

  return {
    canvasWrapRef,
    dragGhostRef,
    pointyOutputRef,
    nodes,
    edges,
    selectedNodeId,
    selectedNode,
    currentTool,
    zoomLevel,
    zoomDisplay,
    workflowName,
    paletteSearch,
    collapsed,
    rightPanelCollapsed,
    bottomTab,
    modalOpen,
    modalName,
    selectedTemplate,
    ctxVisible,
    ctxX,
    ctxY,
    ctxTargetId,
    ctxIsCanvas,
    liveEdgeD,
    connectingHoverId,
    paletteWidth,
    rightPanelWidth,
    bottomPanelHeight,
    edgePaths,
    copyBtnFlash,
    canvasEmpty,
    filteredSections,
    pointyHtml,
    setTool,
    zoom,
    fitCanvas,
    toggleSection,
    metaFor,
    srcColor,
    eventAbbr,
    addNode,
    deleteNode,
    duplicateNode,
    selectNode,
    onCanvasMouseDown,
    onNodeBodyPointerDown,
    onOutputPortDown,
    onInputPortDown,
    startPaletteResize,
    startRightPanelResize,
    startBottomResize,
    onNodeContextMenu,
    onCanvasContextMenu,
    hideCtx,
    ctxDelete,
    ctxDuplicate,
    clearCanvas,
    removeEdge,
    onPaletteDragStart,
    onPaletteDragEnd,
    onCanvasDragOver,
    onCanvasDrop,
    openNewWorkflowModal,
    closeModal,
    pickTemplate,
    confirmNewWorkflow,
    copyPointy,
    onEdgeEnter,
    onEdgeLeave,
    patchNode,
    paletteStripeColor,
  }
}
